"""
Django settings for farm_store project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--i1^@ppa_8v2$2*x###f7%aik$w+6*=j^oqs$-ynqre9q(-iyz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['Anatolevich99.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'products',
    'accounts',
    'parler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'farm_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.cart',
            ],
            'builtins': [ # <--- УБЕДИТЕСЬ, ЧТО ЭТО ЕСТЬ
                'django.templatetags.i18n',
            ]
        },
    },
]

WSGI_APPLICATION = 'farm_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static', # Это укажет Django искать статику в папке `static` в корне проекта
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CART_SESSION_ID = 'cart'

# Email settings for real SMTP (Gmail example)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587             # Порт для TLS (рекомендуется)
EMAIL_USE_TLS = True         # Использовать TLS шифрование
EMAIL_USE_SSL = False        # Не использовать SSL, если используем TLS (они взаимоисключающие)

# ВАШ РЕАЛЬНЫЙ GMAIL АДРЕС, С КОТОРОГО БУДУТ ОТПРАВЛЯТЬСЯ ПИСЬМА
EMAIL_HOST_USER = 'anatolevichandrey182@gmail.com'

# ВАШ 16-ЗНАЧНЫЙ ПАРОЛЬ ПРИЛОЖЕНИЯ GOOGLE (НЕ ОСНОВНОЙ ПАРОЛЬ GMAIL!)
EMAIL_HOST_PASSWORD = 'cuqv vujo lfnx wjnd'

# Адрес по умолчанию, с которого отправляются письма
DEFAULT_FROM_EMAIL = 'anatolevichandrey182@gmail.com'

# Сюда будут приходить уведомления о новых заказах (ваш email)
ORDER_NOTIFICATION_EMAILS = ['anatolevichandrey182@gmail.com'] # <--- МОЖНО УКАЗАТЬ НЕСКОЛЬКО ЧЕРЕЗ ЗАПЯТУЮ

# Адреса для получения уведомлений об ошибках Django
ADMINS = [
    ('Anatolevich', 'anatolevichandrey182@gmail.com'),
]
MANAGERS = ADMINS # Менеджеры получают все сообщения об ошибках

LOGIN_REDIRECT_URL = 'products:product_list' # Куда перенаправлять после успешного входа
LOGOUT_REDIRECT_URL = 'products:product_list' # Куда перенаправлять после выхода

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru' # Язык по умолчанию

# Список доступных языков
LANGUAGES = [
    ('ru', _('Russian')),
    ('en', _('English')),
]

TIME_ZONE = 'UTC'
USE_I18N = True # Включает систему перевода Django
USE_TZ = True

# Путь, где Django будет искать файлы с переводами
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


PARLER_LANGUAGES = {
    None: (
        {'code': 'ru'},
        {'code': 'en'},
    ),
    'default': {
        'fallback': 'ru',          # Язык по умолчанию, если перевод не найден
        'hide_untranslated': False,   # Показывать ли объекты, у которых нет перевода
    }
}