# Generated by Django 5.2.3 on 2025-06-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('g', 'г'), ('pc', 'шт.'), ('l', 'л')], default='pc', max_length=2, verbose_name='Единица измерения'),
        ),
    ]
